"""
Scheduling models.

SlotTemplate   — configures which slots to generate for a branch/service combo.
BookingSlot    — a concrete available slot (generated nightly by Celery Beat).
Booking        — a customer's reservation of a slot.
"""
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from apps.common.models import TenantScopedModel, SoftDeleteManager, AllObjectsManager


class SlotTemplate(TenantScopedModel):
    """
    Blueprint for generating BookingSlots.

    A template covers: a branch, optionally a specific service,
    the slot duration, max concurrent bookings, and active weekdays.
    Nightly Celery task `generate_booking_slots` materialises these
    into BookingSlot rows N days ahead.
    """

    branch = models.ForeignKey("catalog.Branch", on_delete=models.CASCADE, related_name="slot_templates")
    # null service = template applies to all services for this branch
    service = models.ForeignKey(
        "catalog.Service", on_delete=models.CASCADE, related_name="slot_templates", null=True, blank=True
    )
    slot_minutes = models.PositiveSmallIntegerField(default=60)
    capacity_per_slot = models.PositiveSmallIntegerField(default=1)
    # Array of weekdays (0=Mon…6=Sun) on which to generate slots
    active_weekdays = ArrayField(
        models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(6)]),
        default=list,
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = "scheduling_slot_template"
        indexes = [models.Index(fields=["branch", "is_active"])]

    def __str__(self) -> str:
        return f"Template({self.branch_id}, {self.slot_minutes}min, cap={self.capacity_per_slot})"


class BookingSlot(TenantScopedModel):
    """
    A materialised, available time slot for a branch.

    Generated by the `generate_booking_slots` Celery task.
    `capacity_left` is decremented (under lock) when a Booking is created.
    """

    branch = models.ForeignKey("catalog.Branch", on_delete=models.CASCADE, related_name="slots")
    # null service = generic slot (any service can book into it)
    service = models.ForeignKey(
        "catalog.Service", on_delete=models.CASCADE, related_name="slots", null=True, blank=True
    )
    date = models.DateField(db_index=True)
    start_time = models.TimeField()
    end_time = models.TimeField()
    capacity_total = models.PositiveSmallIntegerField(default=1)
    capacity_left = models.PositiveSmallIntegerField(default=1)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = "scheduling_booking_slot"
        unique_together = [("branch", "service", "date", "start_time")]
        indexes = [
            models.Index(fields=["branch", "date", "is_active"]),
            models.Index(fields=["tenant", "date", "is_active"]),
        ]

    def __str__(self) -> str:
        return f"Slot({self.branch_id} {self.date} {self.start_time}-{self.end_time}, left={self.capacity_left})"

    @property
    def is_available(self) -> bool:
        return self.is_active and self.capacity_left > 0


class Booking(TenantScopedModel):
    """
    A customer's booking of a service slot.

    Status machine
    --------------
    pending → confirmed → assigned → en_route → in_progress → completed
    Any non-terminal state → cancelled | no_show
    """

    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        CONFIRMED = "confirmed", "Confirmed"
        ASSIGNED = "assigned", "Staff Assigned"
        EN_ROUTE = "en_route", "En Route"
        IN_PROGRESS = "in_progress", "In Progress"
        COMPLETED = "completed", "Completed"
        CANCELLED = "cancelled", "Cancelled"
        NO_SHOW = "no_show", "No Show"

    class LocationType(models.TextChoices):
        BRANCH = "branch", "Branch"
        MOBILE = "mobile", "Mobile / At-Home"

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="bookings")
    service = models.ForeignKey("catalog.Service", on_delete=models.PROTECT, related_name="bookings")
    branch = models.ForeignKey(
        "catalog.Branch", on_delete=models.PROTECT, related_name="bookings", null=True, blank=True
    )
    slot = models.ForeignKey(BookingSlot, on_delete=models.PROTECT, related_name="bookings")
    vehicle = models.ForeignKey(
        "accounts.Vehicle", on_delete=models.SET_NULL, null=True, blank=True, related_name="bookings"
    )

    status = models.CharField(max_length=15, choices=Status.choices, default=Status.PENDING, db_index=True)
    location_type = models.CharField(max_length=10, choices=LocationType.choices, default=LocationType.BRANCH)

    # Mobile/at-home delivery address
    address = models.ForeignKey(
        "accounts.Address", on_delete=models.SET_NULL, null=True, blank=True, related_name="bookings"
    )
    mobile_lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    mobile_lng = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)

    # Staff assignment (populated when status → assigned)
    assigned_staff = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assigned_bookings",
    )

    # Payment link
    payment = models.ForeignKey(
        "payments.Payment",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="bookings",
    )

    # Money — snapshot at booking time (never recomputed from service)
    price_charged = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=3, default="SAR")

    # Idempotency
    idempotency_key = models.CharField(max_length=255, blank=True, db_index=True)

    # Cancellation
    cancellation_reason = models.TextField(blank=True)
    cancelled_at = models.DateTimeField(null=True, blank=True)

    # Scheduling metadata
    scheduled_date = models.DateField(db_index=True)
    scheduled_start = models.TimeField()

    objects = SoftDeleteManager()
    all_objects = AllObjectsManager()

    class Meta:
        db_table = "scheduling_booking"
        indexes = [
            models.Index(fields=["user", "status"]),
            models.Index(fields=["tenant", "status", "scheduled_date"]),
            models.Index(fields=["assigned_staff", "status"]),
        ]

    def __str__(self) -> str:
        return f"Booking#{self.pk}({self.user_id}, {self.status}, {self.scheduled_date})"


class RecurringBookingRule(TenantScopedModel):
    """
    Time-based rule to auto-create recurring bookings for a customer.

    The `process_recurring_rules` Celery task runs nightly and creates
    upcoming Bookings when they fall within the configured lead-time window.

    No geofence auto-charge — time-based only (per spec §13).
    """

    class Frequency(models.TextChoices):
        WEEKLY = "weekly", "Every Week"
        BIWEEKLY = "biweekly", "Every 2 Weeks"
        MONTHLY = "monthly", "Every Month"

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="recurring_rules"
    )
    service = models.ForeignKey("catalog.Service", on_delete=models.PROTECT, related_name="recurring_rules")
    branch = models.ForeignKey(
        "catalog.Branch", on_delete=models.PROTECT, null=True, blank=True, related_name="recurring_rules"
    )
    frequency = models.CharField(max_length=10, choices=Frequency.choices)
    # Preferred day (0=Mon…6=Sun) and time for each recurrence
    preferred_weekday = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(6)]
    )
    preferred_time = models.TimeField()
    location_type = models.CharField(
        max_length=10,
        choices=[("branch", "Branch"), ("mobile", "Mobile")],
        default="branch",
    )
    address = models.ForeignKey(
        "accounts.Address", on_delete=models.SET_NULL, null=True, blank=True
    )
    vehicle = models.ForeignKey(
        "accounts.Vehicle", on_delete=models.SET_NULL, null=True, blank=True
    )
    # The payment method to charge when auto-creating; wallet or card token
    default_payment_method = models.CharField(max_length=15, default="wallet")
    is_active = models.BooleanField(default=True, db_index=True)
    # Track when the last booking was auto-created to avoid double-creation
    last_booking_date = models.DateField(null=True, blank=True)

    class Meta:
        db_table = "scheduling_recurring_rule"
        indexes = [models.Index(fields=["user", "is_active"])]

    def __str__(self) -> str:
        return f"RecurringRule({self.user_id}, {self.frequency}, wd={self.preferred_weekday})"
