import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("accounts", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="shop/categories/")),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="common.tenant")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="children", to="shop.category")),
            ],
            options={"db_table": "shop_category", "ordering": ["ordering", "name"]},
        ),
        migrations.AlterUniqueTogether(name="category", unique_together={("tenant", "slug")}),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("compare_at_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("track_inventory", models.BooleanField(default=True)),
                ("car_type_tags", models.JSONField(blank=True, default=list)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("sku", models.CharField(blank=True, max_length=100)),
                ("weight_grams", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="shop.category")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="common.tenant")),
            ],
            options={"db_table": "shop_product"},
        ),
        migrations.AlterUniqueTogether(name="product", unique_together={("tenant", "slug")}),
        migrations.AddIndex(model_name="product", index=models.Index(fields=["tenant", "is_active"], name="shop_pr_tenant_active_idx")),
        migrations.AddIndex(model_name="product", index=models.Index(fields=["category", "is_active"], name="shop_pr_cat_active_idx")),
        migrations.AddIndex(model_name="product", index=models.Index(fields=["brand", "is_active"], name="shop_pr_brand_active_idx")),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("url", models.URLField(max_length=500)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="shop.product")),
            ],
            options={"db_table": "shop_product_image", "ordering": ["ordering"]},
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="common.tenant")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="cart", to=settings.AUTH_USER_MODEL)),
                ("promo_code", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="payments.promocode")),
            ],
            options={"db_table": "shop_cart"},
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("cart", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="shop.cart")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shop.product")),
            ],
            options={"db_table": "shop_cart_item"},
        ),
        migrations.AlterUniqueTogether(name="cartitem", unique_together={("cart", "product")}),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending","Pending"),("paid","Paid"),("processing","Processing"),("shipped","Shipped"),("delivered","Delivered"),("cancelled","Cancelled"),("refunded","Refunded")], db_index=True, default="pending", max_length=15)),
                ("delivery_method", models.CharField(choices=[("pickup","Branch Pickup"),("delivery","Home Delivery")], default="pickup", max_length=10)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("discount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("shipping_fee", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, max_length=255)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="common.tenant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to=settings.AUTH_USER_MODEL)),
                ("shipping_address", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="accounts.address")),
                ("promo_code", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="payments.promocode")),
                ("payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="orders", to="payments.payment")),
            ],
            options={"db_table": "shop_order"},
        ),
        migrations.AddIndex(model_name="order", index=models.Index(fields=["user", "status"], name="shop_or_user_status_idx")),
        migrations.AddIndex(model_name="order", index=models.Index(fields=["tenant", "status"], name="shop_or_tenant_status_idx")),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("quantity", models.PositiveSmallIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="shop.order")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="shop.product")),
            ],
            options={"db_table": "shop_order_item"},
        ),
    ]
